/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElRow: typeof import('element-plus/es')['ElRow']
}
