/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Industry: typeof import('./src/components/Industry.vue')['default']
    Portfolio: typeof import('./src/components/Portfolio.vue')['default']
    Service: typeof import('./src/components/Service.vue')['default']
    Touch: typeof import('./src/components/Touch.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    Why: typeof import('./src/components/Why.vue')['default']
  }
}
